# Generated by Django 5.1.3 on 2024-11-17 21:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField()),
                ('push_notifications', models.BooleanField()),
                ('frequency', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='PrivacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.BooleanField()),
                ('data_sharing', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('file_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='userdata',
            options={'verbose_name_plural': 'User Data'},
        ),
        migrations.AddField(
            model_name='userdata',
            name='notification_settings',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='api.notificationsettings'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='privacy_settings',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='api.privacysettings'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font', models.CharField(max_length=100)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.theme')),
            ],
        ),
        migrations.AddField(
            model_name='userdata',
            name='theme_settings',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='api.themesettings'),
            preserve_default=False,
        ),
    ]
